matrix:
  include:
    - language: java
      jdk:
        - openjdk8
      env:
        global:
          - secure: FxpoMJmkjBKy0qsPMLcs9fpiquJ217s5qlRC9sCTf7GWkDydqDV8ZAIy9LihOf17qH/m0U8Ii6BmOeH/V0Oa1CPhTvHVrLw+aBN6OrMWUs9EmPqa7pCpk+p6Rr81/matzfbKjTGBsSqFMAj5Aj4VpR7RTyQEBh+cZgORgbrnatU=
          - secure: QS9IQXvglj/DPaqY69AEEegEylJ/7dyqElm++LQMsOrfVCr1MUnPo2xBqciThsrBSQsqP+Llc+xGWK+/iFTxHgHhJuvcZmyZb9i+M0ISqoJkluZwZjIzYcBe3N7mo36JKqBzIkTgVvvkXPr5pn8PmYVKlgIzV2QbYRT42NIFn4U=
      branches:
        except:
          - gh-pages
      cache:
        directories:
          - "$HOME/.m2/repository"
      before_script: sed -i "s@-dev@-dev#$TRAVIS_BUILD_NUMBER@" BetonQuest-core/src/main/resources/plugin.yml
      install: true
      script: mvn clean package -Drelease
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          curl -F "pass=$pass" -F "id=$TRAVIS_BUILD_NUMBER" -F "hash=$TRAVIS_COMMIT" -F "branch=$TRAVIS_BRANCH" -F "plugin=@target/BetonQuest.jar" https://betonquest.pl";
          chmod +x discord.sh;
          ./discord.sh;
          fi
    - language: python
      python: 3.6
      branches:
        except:
          - gh-pages
      cache:
        pip: true
      script:
        - if [ -n "${DEPLOY_KEY}" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then
          eval `ssh-agent -s`;
          ssh-add <(echo "$DEPLOY_KEY" | base64 -d);
          git config user.name "Automatic Publish";
          git remote add gh-token "git@github.com:${TRAVIS_REPO_SLUG}";
          git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
          echo "Pushing to github";
          mkdocs gh-deploy -v --clean --remote-name gh-token;
          fi;