site_name: BetonQuest
site_author: BetonQuest Organisation
site_url: https://docs.betonquest.org/
site_dir: target/docs
docs_dir: documentation
repo_name: BetonQuest on GitHub
edit_uri: /BetonQuest/BetonQuest/edit/main_v1.12/documentation/
repo_url: https://github.com/BetonQuest/BetonQuest
copyright: 'Â© 2023  BetonQuest Organisation. GPLv3'


extra_css:
  - 'webCode/css/centered.css'
  - 'webCode/css/contentAreaFullWidth.css'


extra_javascript:
  - 'webCode/js/copyLinkToClipboard.js'

# More info on this theme: https://squidfunk.github.io/mkdocs-material
theme:
  name: material
  language: en
  custom_dir: 'documentation/_custom_theme'
  features:
    - content.code.copy
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: media/design/BQIcon1k.png
  favicon: media/design/favicon.ico



# See the following for docs on these extensions: https://squidfunk.github.io/mkdocs-material/extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: ğŸ”—

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

extra:
  version:
    provider: mike
    default:
      - RELEASE
      - DEV
  analytics:
    provider: google
    property: G-VEBGTNXWEL

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: fontawesome/solid/faucet-drip
      link: https://spigotmc.org/resources/2117/
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: octicons/mail-16
      link: mailto://contact@betonquest.org

#Notice that here are a few strange looking hairspaces in here.
#They make the space between the emojis and the text look equal
nav:
  - 'Home':
      - 'ğŸ‘‹ Welcome!': index.md
      - 'Overview':
          - 'âœ¨ Features': Features.md
          - 'ğŸ‘” â€ŠFor Owners': For-Owners.md
          - 'ğŸ¨ For Questers': For-Questers.md
  - 'Learn Beton':
      - 'ğŸ‘‹ Welcome!': Learn-Beton/Welcome.md
      - 'Getting Started':
          - 'ğŸ’» Setting up a local test server': Learn-Beton/Getting-Started/Setting-up-a-local-test-server.md
          - 'ğŸ“¥ Installing BetonQuest': Learn-Beton/Getting-Started/Installing-BetonQuest.md
          - 'âœ’ï¸ Setting up the editor': Learn-Beton/Getting-Started/Setting-up-the-editor.md
          - 'ğŸ“‘ YAML for questers': Learn-Beton/Getting-Started/YAML-for-questers.md
          - 'ğŸ“ Learn BetonQuest': Learn-Beton/Getting-Started/Learn-BetonQuest.md
      - 'â“ Frequently Asked Questions':
          - 'ğŸ¤” â€ŠGeneral FAQ': Learn-Beton/Frequently-Asked-Questions.md

  - 'User Documentation':
      - 'General':
          - 'ğŸ“š â€Šâ€ŠReference': User-Documentation/Reference.md
          - 'ğŸ’¬ â€ŠConversations': User-Documentation/Conversations.md

      - 'Types':
          - 'âœ”ï¸ Objectives List': User-Documentation/Objectives-List.md
          - 'âš™ï¸ Events List': User-Documentation/Events-List.md
          - 'â€Šâ€Šâ“ â€Šâ€Šâ€ŠConditions List': User-Documentation/Conditions-List.md
          - 'ğŸ¤ Compatibility List': User-Documentation/Compatibility.md
          - 'ğŸ”® â€Šâ€ŠVariables List': User-Documentation/Variables-List.md

      - 'Notifications':
          - 'ğŸ”Š â€Šâ€ŠSettings': User-Documentation/Notification-Settings.md
          - "ğŸ·ï¸ â€Šâ€ŠIO's & Categories": User-Documentation/Notification-IO's-&-Categories.md

      - 'Technical':
          - 'ğŸ”’ Permissions & Commands': User-Documentation/Commands-and-permissions.md
          - 'ğŸ“¥ Updating': User-Documentation/Updating-and-Backups.md
          - 'ğŸ”§ â€ŠConfiguration': User-Documentation/Configuration.md
          - 'ğŸ—ƒï¸ Changelog': User-Documentation/CHANGELOG.md

  - 'Developer Documentation':
      - 'ğŸ“š Contributing Guidelines': Developer-Documentation/Contributing-Guidelines.md
      - 'âš™ï¸ API': Developer-Documentation/API.md
      - 'ğŸ­ Versioning & Releasing': Developer-Documentation/Versioning-and-Releasing.md
  - 'Contributing':
      - 'ğŸ¤ Overview': Contributing/Contributing.md
      - 'Docs':
          - 'ğŸ”§ Setup': Contributing/Documentation/Setup.md
          - 'ğŸ“š Guidelines': Contributing/Documentation/Guidelines.md
      - 'Sponsorships':
          - 'ğŸ’² Patreon': Contributing/Sponsors.md
  - 'Downloads': Downloads/index.md


