site_name: BetonQuest
site_author: BetonQuest Organisation
site_url: https://docs.betonquest.org/
site_dir: target/documentation
docs_dir: documentation
repo_name: BetonQuest on GitHub
edit_uri: /BetonQuest/BetonQuest/edit/master/documentation/
repo_url: https://github.com/BetonQuest/BetonQuest
copyright: 'Â© 2020  BetonQuest Organisation. GPLv3'


extra_css:
  - 'webCode/css/admonition.css'
  - 'webCode/css/button.css'
  - 'webCode/css/centered.css'
  - 'webCode/css/contentAreaFullWidth.css'
  - 'webCode/css/superFences.css'

extra_javascript:
  - 'webCode/js/copyLinkToClipboard.js'

# More info on this theme: https://squidfunk.github.io/mkdocs-material
theme:
  name: material
  custom_dir: 'custom_theme/'
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: media/brand/Icon/Icon1k.png
  favicon: media/brand/Icon/Icon32.ico



# See the following for docs on these extensions: https://squidfunk.github.io/mkdocs-material/extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: ğŸ”—

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/betonquest
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: fontawesome/solid/archive
      link: https://betonquest.org/old
    - icon: fontawesome/solid/faucet
      link: https://spigotmc.org/resources/betonquest.2117/

#Notice that here are a few strange looking hairspaces in here.
#They make the space between the emojis and the text look equal
nav:
  - 'ğŸš€ Home': index.md
  - 'ğŸ“ Tutorials':
      - 'ğŸ‘‹ Welcome!': Tutorials/Welcome.md
      - 'Getting Started':
          - 'ğŸ’» Setting up a local test server': Tutorials/Getting-Started/Setting-up-a-local-test-server.md
          - 'ğŸ“¥ Installing BetonQuest': Tutorials/Getting-Started/Installing-BetonQuest.md
          - 'âœ’ï¸ Setting up the editor': Tutorials/Getting-Started/Setting-up-the-editor.md
          - 'ğŸ“‘ YAML for questers': Tutorials/Getting-Started/YAML-for-questers.md
          - 'â±ï¸ â€Šâ€ŠQuick Start Tutorial': Tutorials/Getting-Started/Quick-Start-Tutorial.md
      - 'â“ Frequently Asked Questions':
          - 'ğŸ¤” â€ŠGeneral FAQ': Tutorials/Frequently-Asked-Questions.md
  - 'ğŸ“š Documentation':
      - 'General':
          - 'ğŸ“š â€Šâ€ŠReference': Documentation/Reference.md
          - 'ğŸ’¬ â€ŠConversations': Documentation/Conversations.md
          - 'â€Šâ€Šâ€ŠğŸ“± â€Šâ€Šâ€Šâ€ŠMenus': Documentation/Menus.md
      - 'Types':
          - 'âœ”ï¸ Objectives List': Documentation/Objectives-List.md
          - 'âš™ï¸ Events List': Documentation/Events-List.md
          - 'â€Šâ€Šâ“ â€Šâ€Šâ€ŠConditions List': Documentation/Conditions-List.md
          - 'ğŸ¤ Compatibility List': Documentation/Compatibility.md
          - 'ğŸ”® â€Šâ€ŠVariables List': Documentation/Variables-List.md
      - 'Notifications':
          - 'ğŸ”Š â€Šâ€ŠSettings': Documentation/Notification-Settings.md
          - "ğŸ·ï¸ â€Šâ€ŠIO's & Categories": Documentation/Notification-IO's-&-Categories.md
      - 'Technical':
          - 'ğŸ”’ Permissions & Commands': Documentation/Commands-and-permissions.md
          - 'ğŸ“¥ Updating': Documentation/Updating-and-Backups.md
          - 'ğŸ”§ â€ŠConfiguration': Documentation/Configuration.md
          - 'ğŸ—ƒï¸ Changelog': Documentation/CHANGELOG.md
  - 'ğŸ”Œ API':
      - 'âš™ï¸ API': API/API.md
  - 'ğŸ§ª Participate':
      - 'ğŸ¤ Overview': Participate/Overview.md
      - 'Code':
          - 'ğŸ“š Contributing Guidelines': Participate/Code/Contributing-Guidelines.md
          - 'ğŸ­ Releasing': Participate/Code/Releasing.md
          - 'ğŸ·ï¸ Versioning': Participate/Code/Versioning.md
      - 'Docs':
          - 'ğŸ”§ Setup': Participate/Docs/Setup.md
          - 'ğŸ“š Guidelines': Participate/Docs/Guidelines.md

google_analytics:
  - UA-164568470-1
  - auto
