INHERIT: ./docs/mkdocs_parent.yml
site_name: BetonQuest
site_author: BetonQuest Organisation
site_url: https://betonquest.org/
repo_name: BetonQuest on GitHub
repo_url: https://github.com/BetonQuest/BetonQuest
copyright: >
  <p id="bqCopyright">© 2014-{CurrentYear} BetonQuest Organisation. GPLv3</p>
  <a href="#__consent">Change cookie settings</a>

extra:
  version:
    provider: mike
    default:
      - RELEASE
      - DEV

  social:
    - icon: brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: brands/opencollective
      link: https://opencollective.com/betonquest
    - icon: brands/modrinth
      link: https://modrinth.com/plugin/betonquest
    - icon: brands/spigot
      link: https://spigotmc.org/resources/2117/
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: brands/mail
      link: mailto://contact@betonquest.org

#Notice that here are a few strange looking hairspaces in here.
#They make the space between the emojis and the text look equal
nav:
  - 'Home': index.md
  - 'Tutorials':
      - 'Overview': Tutorials/Overview.md
      - 'Getting Started':
          - 'About': Tutorials/Getting-Started/About.md
          - 'Setup Guide':
              - 'Setting up a Test Server': Tutorials/Getting-Started/Setup-Guide/Setting-up-a-Test-Server.md
              - 'Installing BetonQuest': Tutorials/Getting-Started/Setup-Guide/Installing-BetonQuest.md
              - 'Setting up VSCode': Tutorials/Getting-Started/Setup-Guide/Setting-up-VSCode.md
          - 'Basics':
              - 'YAML': Tutorials/Getting-Started/Basics/YAML-Basics.md
              - 'Conversations': Tutorials/Getting-Started/Basics/Conversations.md
              - '    Events': Tutorials/Getting-Started/Basics/Events.md
              - 'Objectives': Tutorials/Getting-Started/Basics/Objectives.md
              - 'Conditions': Tutorials/Getting-Started/Basics/Conditions.md
      - 'Features':
          - 'Tracking Quest Progress':
              - 'Overview': Tutorials/Features/Tracking-Quest-Progress/Overview.md
              - 'Tags': Tutorials/Features/Tracking-Quest-Progress/Tags.md
      - 'Tools':
          - 'Handling YAML Errors': Tutorials/Tools/YAML-Errors.md
      - 'Syntax':
          - 'Quest Packages': Tutorials/Syntax/Quest-Packages.md
  - 'Documentation':
      - 'Overview': Documentation/Overview.md

      - 'Scripting':
          - 'About Scripting': Documentation/Scripting/About-Scripting.md
          - 'Packages & Templates': Documentation/Scripting/Packages-&-Templates.md
          - 'Events List': Documentation/Scripting/Building-Blocks/Events-List.md
          - 'Objectives List': Documentation/Scripting/Building-Blocks/Objectives-List.md
          - 'Conditions List': Documentation/Scripting/Building-Blocks/Conditions-List.md
          - 'Integration List': Documentation/Scripting/Building-Blocks/Integration-List.md
          - 'Variables List': Documentation/Scripting/Building-Blocks/Variables-List.md
          - 'Additional Features':
              - 'Schedules': Documentation/Scripting/Schedules.md
              - 'Parties': Documentation/Scripting/Parties.md
              - 'Data Formats': Documentation/Scripting/Data-Formats.md
              - 'Quoting & advanced YAML': Documentation/Scripting/Quoting-&-YAML.md

      - 'Features':
          - 'Conversations': Documentation/Features/Conversations.md
          - 'Quest Menus':
              - 'Menus': Documentation/Features/Menus/Menu.md
              - 'Menu Example': Documentation/Features/Menus/Example.md
              - 'Elements': Documentation/Features/Menus/Elements.md
              - 'Menu Settings': Documentation/Features/Menus/Config.md
          - 'Additional Features':
              - 'Journal': Documentation/Features/Journal.md
              - 'Quest Items': Documentation/Features/Items.md
              - 'Quest Cancelers': Documentation/Features/Quest-Cancelers.md

      - 'Visual Effects':
          - 'Notifications':
              - 'Settings': Documentation/Visual-Effects/Notifications/Notification-Settings.md
              - "IO's & Categories": Documentation/Visual-Effects/Notifications/Notification-IO's-&-Categories.md
          - 'NPC Effects':
              - 'NPC Hiding': Documentation/Visual-Effects/NPC-Effects/NPC-Hiding.md
              - 'NPC Holograms': Documentation/Visual-Effects/NPC-Effects/NPC-Holograms.md
          - 'Additional Effects':
              - 'Quest Holograms': Documentation/Visual-Effects/Additional-Effects/Quest-Holograms.md
              - 'Player Hider': Documentation/Visual-Effects/Additional-Effects/Player-Hider.md

      - 'Configuration':
          - 'Configuration': Documentation/Configuration/Configuration.md
          - 'Permissions & Commands': Documentation/Configuration/Commands-and-permissions.md
          - 'Version Changes':
              - 'Updating': Documentation/Configuration/Version-Changes/Updating.md
              - 'Migration 1.X to 2.X': Documentation/Configuration/Version-Changes/Migration-1-2.md
              - 'Migration 2.X to 3.X': Documentation/Configuration/Version-Changes/Migration-2-3.md
              - 'Changelog': Documentation/CHANGELOG.md

      - 'Frequently Asked Questions':
          - 'General FAQ': Documentation/Frequently-Asked-Questions.md
  - 'API':
      - 'Overview': API/Overview.md
      - 'Obtaining API': API/Obtaining-API.md
      - APIs:
          - 'Legacy API': API/Legacy-API.md
          - 'Instruction': API/Instruction.md
          - 'Writing Implementations': API/Writing-Implementations.md
          - 'Logging': API/Logging.md
          - 'Configuration Files': API/ConfigurationFiles.md
          - 'Bukkit Configurations': API/BukkitConfigurations.md
          - 'Schedules': API/Schedules.md
  - 'Participate':
      - 'Overview': Participate/Overview.md
      - 'Donate Money': Participate/Donating-Money.md
      - 'Setup Project': Participate/Setup-Project.md
      - Process:
          - 'Create a new Branch': Participate/Process/Create-a-new-Branch.md
          - 'Changing Docs':
              - 'Workflow': Participate/Process/Docs/Workflow.md
              - 'Fundamental Principles': Participate/Process/Docs/Principles.md
              - 'Guidelines': Participate/Process/Docs/Guidelines.md
              - 'Writing Tutorials': Participate/Process/Docs/Writing-Tutorials.md
              - 'mkdocs Customizations': Participate/Process/Docs/Customizations.md
          - 'Changing Code':
              - 'Workflow': Participate/Process/Code/Workflow.md
              - 'Checking Requirements': Participate/Process/Code/Checking-Requirements.md
              - 'Adding a Dependency': Participate/Process/Code/Adding-a-new-Dependency.md
              - 'Writing JUnit Tests': Participate/Process/Code/Writing-JUnit-Tests.md
          - 'Maintaining the Changelog': Participate/Process/Maintaining-the-Changelog.md
          - 'Submitting Changes': Participate/Process/Submitting-Changes.md
      - Misc:
          - 'Versioning & Releasing': Participate/Misc/Versioning-and-Releasing.md
  - 'Downloads': Downloads/index.md
