site_name: BetonQuest - UNOFFICIAL
site_author: Co0sh and contributors
site_url: https://betonquest.pl
site_dir: target/docs
docs_dir: docs
repo_name: BetonQuest/BetonQuest
repo_url: https://github.com/BetonQuest/BetonQuest
edit_uri: ""
copyright: 'Â© 2020  Jakub "Co0sh" Sapalski  & Contributers. GPLv3'


extra_css:
  - 'webCode/css/mkpdf.css'
  - 'webCode/css/version_select.css'
  - 'webCode/css/superFences.css'

extra_javascript:
  - 'webCode/js/version_select.js'

# More info on this theme: https://squidfunk.github.io/mkdocs-material
theme:
  name: material
  language: en
  features:
    - tabs
    - instant
  palette:
    primary: indigo
    accent: indigo
    scheme: slate
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/design/icon.png
  favicon: images/design/favicon.ico



# See the following for docs on these extensions: https://squidfunk.github.io/mkdocs-material/extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - footnotes

# Bundie's Tip: Disable mkpdfs whilst using `mkdocs serve` on a local machine. But be carefull not to commit that.
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - mkpdfs:
      author: Co0sh and contributors
      toc_title: Table of contents
      output_path: pdf/BetonQuest.pdf
      design: docs/webCode/css/pdf.css


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: fontawesome/solid/faucet
      link: https://spigotmc.org/resources/betonquest.2117/
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: fontawesome/solid/archive
      link: https://betonquest.pl

nav:
  - 'Home':
      - 'Welcome!': index.md
      - For-Admins.md
      - For-Questers.md
      - Features.md
  - 'Learn Beton':
      - Learn-Beton/Welcome.md
      - Learn-Beton/Frequently-Asked-Questions.md
      - Learn-Beton/Installation-and-Configuration.md
      - Learn-Beton/Quick-start-tutorial.md
      - Learn-Beton/Tips-and-tricks.md
      - 'Getting Started':
          - Learn-Beton/Getting-Started/Setting-up-a-local-test-server.md
          - Learn-Beton/Getting-Started/Installing-BetonQuest.md
          - Learn-Beton/Getting-Started/Setting-up-the-editor.md
          - Learn-Beton/Getting-Started/YAML-for-questers.md
  - 'User Documentation':
      - User-Documentation/Commands-and-permissions.md
      - User-Documentation/Compatibility.md
      - User-Documentation/Conditions-List.md
      - User-Documentation/Events-List.md
      - User-Documentation/Notifications.md
      - User-Documentation/Objectives-List.md
      - User-Documentation/Reference.md
      - User-Documentation/Variables-List.md
      - User-Documentation/CHANGELOG.md
  - 'Developer Documentation':
      - Developer-Documentation/Info-for-developers.md
      - Developer-Documentation/Releasing.md
      - Developer-Documentation/Versioning.md
  - 'Contributing':
      - Contributing/Contributing.md
      - 'Old': Contributing/old_contributing.md
      - Contributing/Docs/Docs.md

google_analytics:
  - UA-164568470-1
  - auto