version: v42
mysql:
  host: ''
  port: ''
  user: ''
  pass: ''
  base: ''
  prefix: betonquest_
language: en
update:
  enabled: true
  download_bugfixes: true
  notify_new_release: true
default_journal_slot: '-1'
max_npc_distance: '5'
default_conversation_IO: chest
combat_delay: '10'
notify_pullback: 'true'
default_package: default
remove_items_after_respawn: 'true'
sounds:
  start: VILLAGER_HAGGLE
  end: VILLAGER_YES
  journal: BAT_TAKEOFF
  update: 'false'
  full: 'false'
cmd_blacklist:
- spawn
hook:
  citizens: 'true'
  mythicmobs: 'true'
  vault: 'true'
  worldguard: 'true'
  skript: 'true'
  mcmmo: 'true'
  effectlib: 'true'
  playerpoints: 'true'
  heroes: 'true'
  magic: 'true'
  denizen: 'true'
  skillapi: 'true'
  quests: 'true'
  shopkeepers: 'true'
  placeholderapi: 'true'
journal:
  chars_per_page: '245'
  one_entry_per_page: 'false'
  reversed_order: 'true'
  hide_date: 'false'
journal_colors:
  date:
    day: '9'
    hour: '6'
  line: '4'
  text: '0'
conversation_colors:
  npc: dark_red
  player: dark_green
  text: green,italic
  answer: gray
  number: yellow
  option: aqua
date_format: dd.MM.yyyy HH:mm
effectlib_npc_effect:
  class: VortexEffect
  iterations: 20
  particle: crit_magic
  helixes: 3
  circles: 1
  grow: 0.1
  radius: 0.5
  delay: 5
  