version: 'v2'
mysql:
  host: ''
  port: ''
  user: ''
  pass: ''
  base: ''
language: en
metrics: 'true'
autoupdate: 'true'
uuid: 'false'
default_journal_slot: '-1'
max_npc_distance: '5'
tellraw: 'false'
journal_colors:
  date:
    day: '9'
    hour: '6'
  line: '4'
  text: '0'
sounds:
  start: 'VILLAGER_HAGGLE'
  end: 'VILLAGER_YES'
  journal: 'BAT_TAKEOFF'
  update: 'false'
  full: 'false'
global_locations: ''