default_close: true
messages:
  en:
    command_no_permission: '&7[&c&l!&7] No permission!'
    menu_do_not_open: '&7[&c&l!&7] No permission!'
    command_usage: '&cUsage:\n&7{1}'
    command_info_reload: '&breloads all/one menu(s)'
    command_info_list: '&bopens specific menu [for a player]'
    command_info_open: '&blists all loaded menus'
    command_invalid_menu: '&7[&c&l!&7] &c{1}&7 is not a loaded menu!'
    command_no_player: '&7[&c&l!&7] Please specify a player!'
    command_invalid_player: '&7[&c&l!&7] There is no player with the name &c{1}&7!'
    command_no_menu: '&7[&c&l!&7] Please specify a menu!'
    command_open_successful: '&7[&a&li&7]&a Successfully opened &7{1}&a!'
    command_reload_successful: '&7[{1}&li&7]{1} Successfully reloaded &7{2}{1} menu(s)!'
    command_reload_failed: '&7[&4&l!&7]&4 Reload failed!'
    command_list: '&e----- &aRPGMenu &e-----\n&aLoaded menus:&e '
    click_to_open: '&bclick to open menu'
  de:
    command_no_permission: '&7[&c&l!&7] Fehlende Berechtigung!'
    menu_do_not_open: '&7[&c&l!&7] Fehlende Berechtigung!'
    command_usage: '&cVerwendung:\n&7{1}'
    command_info_reload: '&blaedt alle/ein Menue(s) neu  '
    command_info_list: '&boeffnet ein Menue[fuer einen Spieler]'
    command_info_open: '&blistet alle geladenen Menues auf'
    command_invalid_menu: '&7[&c&l!&7] Es ist kein Menue mit der Id &c{1}&7 geladen!'
    command_invalid_player: '&7[&c&l!&7] Es ist kein Spieler mit dem Namen &c{1}&7 online!'
    command_no_player: '&7[&c&l!&7] Bitte gib einen Spieler an!'
    command_no_menu: '&7[&c&l!&7] Bitte gib ein Menue an!'
    command_open_successful: '&7[&a&li&7]&a Menue &7{1}&a wurde geoeffnet!'
    command_reload_successful: '&7[{1}&li&7]{1} Reload erfolgreich! &7{2}{1} Menue(s) wurden geladen!'
    command_reload_failed: '&7[&4&l!&7]&4 Reload fehlgeschlagen!'
    command_list: '&e----- &aRPGMenu &e-----\n&aGeladene Menues:&e '
    click_to_open: '&bklicke um das Menue zu oeffnen'
  fr:
    command_no_permission: '&7[&c&l!&7] Pas de permissions!'
    menu_do_not_open: '&7[&c&l!&7] Pas de permissions!'
    command_usage: '&cusage:\n&7{1}'
    command_info_reload: '&brecharges tous/un menu(s)'
    command_info_list: '&bouvre un menu [pour un joueur]'
    command_info_open: '&bliste tous les menus'
    command_invalid_menu: '&7[&c&l!&7] &c{1}&7 n''est pas un menu connu!'
    command_no_player: '&7[&c&l!&7] Veuillez specifier un joueur!'
    command_invalid_player: '&7[&c&l!&7] Il n''y a pas de joueur avec le nom &c{1}&7!'
    command_no_menu: '&7[&c&l!&7] Veuillez specifier un menu!'
    command_open_successful: '&7[&a&li&7]&7{1}&a a ete ouvert!'
    command_reload_successful: '&7[{1}&li&7]{1} Recharge &7{2}{1} menu(s) avec succes!'
    command_reload_failed: '&7[&4&l!&7]&4 Le rechargement a echoue!'
    command_list: '&e----- &aRPGMenu &e-----\n&aMenus connu:&e '
    click_to_open: '&bcliquez pour ouvrir le menu'
  it:
    command_no_permission: '&7[&c&l!&7] Non hai i permessi!'
    menu_do_not_open: '&7[&c&l!&7] Non hai i permessi!'
    command_usage: '&cUso:\n&7{1}'
    command_info_reload: '&bricarica tutti/un menu'
    command_info_list: '&bapre un menu specifico [per un giocatore]'
    command_info_open: '&belenca tutti i menu conosciuti'
    command_invalid_menu: '&7[&c&l!&7] &c{1}&7 non e un menu conosciuto!'
    command_no_player: '&7[&c&l!&7] Per favore specifica un giocatore!'
    command_invalid_player: '&7[&c&l!&7] Non c''e nessun giocatore chiamato &c{1}&7!'
    command_no_menu: '&7[&c&l!&7] Per favore specifica un menu!'
    command_open_successful: '&7[&a&li&7]&a &7{1}&a aperto con successo!'
    command_reload_successful: '&7[{1}&li&7]{1} Ricaricati con successo &7{2}{1} menu!'
    command_reload_failed: '&7[&4&l!&7]&4 Ricaricamento fallito!'
    command_list: '&e----- &aRPGMenu &e-----\n&aMenu caricati:&e '
    click_to_open: '&bclicca per aprire il menu'
  es:
    command_no_permission: '&7[&c&l!&7] No tienes permisos!'
    menu_do_not_open: '&7[&c&l!&7] No tienes permisos!'
    command_usage: '&cUso:\n&7{1}'
    command_info_reload: '&brecargar todo/un menu(s)'
    command_info_list: '&babre un menu especifico [para un jugador]'
    command_info_open: '&bLista todos los menus cargados'
    command_invalid_menu: '&7[&c&l!&7] &c{1}&7 no es un menu cargado!'
    command_no_player: '&7[&c&l!&7] Por favor especifica el jugador!'
    command_invalid_player: '&7[&c&l!&7] No hay ningun jugador con el nombre &c{1}&7!'
    command_no_menu: '&7[&c&l!&7] Por favor especifica el menu!'
    command_open_successful: '&7[&a&li&7]&a Abierto con exito &7{1}&a!'
    command_reload_successful: '&7[{1}&li&7]{1} Recargado con exito &7{2}{1} menu(s)!'
    command_reload_failed: '&7[&4&l!&7]&4 Recarga fallida!'
    command_list: '&e----- &aRPGMenu &e-----\n&aMenus cargados:&e '
    click_to_open: '&bHaz clic para abrir el menu'
