site_name: BetonQuest - UNOFFICIAL
site_author: Co0sh and contributors
site_url: https://betonquest.org/old
site_dir: target/documentation
docs_dir: ./../documentation
repo_name: BetonQuest on GitHub
edit_uri: /BetonQuest/BetonQuest/edit/master/documentation/
repo_url: https://github.com/BetonQuest/BetonQuest
copyright: 'Â© 2020  Jakub "Co0sh" Sapalski  & Contributers. GPLv3'


extra_css:
  - 'webCode/css/mkpdf.css'
  - 'webCode/css/version_select.css'
  - 'webCode/css/superFences.css'
  - 'webCode/css/centered.css'
  - 'webCode/css/contentAreaFullWidth.css'
  - 'webCode/css/admonition.css'

extra_javascript:
  - 'webCode/js/version_select.js'

# More info on this theme: https://squidfunk.github.io/mkdocs-material
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.highlight
    - search.suggest
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: media/design/BQIcon2k.png
  favicon: media/design/favicon.ico



# See the following for docs on these extensions: https://squidfunk.github.io/mkdocs-material/extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: ğŸ”—

# Bundie's Tip: Disable mkpdfs whilst using `mkdocs serve` on a local machine. But be carefull not to commit that.
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - mkpdfs:
      author: Co0sh and contributors
      toc_title: Table of contents
      output_path: pdf/BetonQuest.pdf
      design: ../documentation/webCode/css/pdf.css


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rK6mfHq
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/betonquest
    - icon: fontawesome/brands/github
      link: https://github.com/BetonQuest/BetonQuest
    - icon: fontawesome/solid/archive
      link: https://betonquest.org/old
    - icon: fontawesome/solid/faucet
      link: https://spigotmc.org/resources/betonquest.2117/

#Notice that here are a few strange looking hairspaces in here. They make the space between the emojis and the text look equal
nav:
  - 'Home':
      - 'Welcome! ğŸ‘‹': index.md
      - For-Owners.md
      - For-Questers.md
      - Features.md
  - 'Learn Beton':
      - Learn-Beton/Welcome.md
      - 'Getting Started':
          - Learn-Beton/Getting-Started/Setting-up-a-local-test-server.md
          - Learn-Beton/Getting-Started/Installing-BetonQuest.md
          - Learn-Beton/Getting-Started/Setting-up-the-editor.md
          - Learn-Beton/Getting-Started/Quick-Start-Tutorial.md
      - Learn-Beton/Frequently-Asked-Questions.md
      - Learn-Beton/Tips-and-tricks.md

  - 'User Documentation':
      - 'General':
        - 'ğŸ“š â€Šâ€ŠReference': User-Documentation/Reference.md
        - 'ğŸ’¬ â€ŠConversations': User-Documentation/Conversations.md

      - 'Types':
          - 'âœ”ï¸ Objectives List': User-Documentation/Objectives-List.md
          - 'âš™ï¸ Events List': User-Documentation/Events-List.md
          - 'â€Šâ€Šâ“ â€Šâ€Šâ€ŠConditions List': User-Documentation/Conditions-List.md
          - 'ğŸ¤ Compatibility List': User-Documentation/Compatibility.md
          - 'ğŸ”® â€Šâ€ŠVariables List': User-Documentation/Variables-List.md

      - 'Notifications:':
        - 'ğŸ”Š â€Šâ€ŠSettings': User-Documentation/Notification-Settings.md
        - "ğŸ·ï¸ â€Šâ€ŠIO's & Categories": User-Documentation/Notification-IO's-&-Categories.md

      - 'Technical:':
        - 'ğŸ”’ Permissions & Commands': User-Documentation/Commands-and-permissions.md
        - 'ğŸ“¥ Updating': User-Documentation/Updating-and-Backups.md
        - 'ğŸ”§ â€ŠConfiguration': User-Documentation/Configuration.md
        - 'ğŸ—ƒï¸ Changelog': User-Documentation/CHANGELOG.md

  - 'Developer Documentation':
      - Developer-Documentation/Contributing-Guidelines.md
      - Developer-Documentation/API.md
      - Developer-Documentation/Releasing.md
      - Developer-Documentation/Versioning.md
  - 'Contributing':
      - 'General':
          - Contributing/Contributing.md
      - 'Docs':
          - Contributing/Documentation/Setup.md
          - Contributing/Documentation/Guidelines.md
      - 'Sponsorships':
          - 'Patreon': Contributing/Sponsors.md


google_analytics:
  - UA-164568470-1
  - auto
