name: Sync Common Files

on:
  schedule:
    - cron: '0 0 * * *' # Runs nightly
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Common Files
        uses: BetonQuest/CommonProjectFiles@main
