name: Sync Common Files

on:
  schedule:
    - cron: '0 0 * * *' # Runs nightly
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'BetonQuest'" # Do not sync for forks

    steps:
      - name: Sync Common Files
        uses: BetonQuest/CommonProjectFiles@main
        with:
          token: ${{ secrets.ALL_REPOSITORIES_ACCESS_TOKEN }}
